name: Build & Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set UTF-8 encoding for .NET
      run: |
        export LANG=en_US.UTF-8
        export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build AulasHumberto.sln
    - name: Test Calculadora
      run: dotnet test Calculadora.Tests/Calculadora.Tests.csproj
    - name: Test Empresa
      run: dotnet test Empresa.Tests/Empresa.Tests.csproj
    - name: Test JogoVelha
      run: dotnet test JogoVelha.Tests/JogoVelha.Tests.csproj
